[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/"
  to = "/de/"
  status = 302
  force = true
  conditions = {Language = ["de"]}
[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  force = true
  conditions = {Language = ["ru"]}
[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true
